### ISSUE TITLE
Associate sensorList id's and element id's

### ISSUE THREAD

**Issue by nafkin2** [htool/Pico2SignalK#2]
Hi!

Thanks for your work on this - this is a great starting point for what I am trying to do. I have converted this to Python3, and am now working on the hard-coding part for my system.

Is there some magic to associating the sensorList id's and element id's, when you add values to sensorList? 

    # Kajuit
    sensorListTmp_id = 22
    element_id = 24

Thanks!

**Comment by htool** [comment]
Hi Nafkin,

There is some logic to it, but that didn't make it in there yet :)

The Pico has a list of sensors that have one or more values. E.g. a temp sensor has 1 value and a battery has i believe 2 (state of charge and voltage).
The type of sensor is listed in the config.
The idea is to map the size of the values (element_ids) to these sensor types and then mapping can be generated.
Now it's manual and you can see the sensorListTmp_id doing +1 between them to set the values from element_id where element_id jumps 1 or more depending on the sensor type.

Run with DEBUG=pico ./pico.py to see more of the initial mapping.

So ideally what should happen:
1. Read config
2. Map positions of element_id to the sensors based on their type
3. Loop over coming data to update values

And further ideally this would become a SignalK plugin which means doing it in NodeJS :)

**Comment by htool** [comment]
BTW, out of curiosity what is it that you're planning to make/do?

**Comment by nafkin2** [comment]
Yeah! I'll give that a shot and see what I can figure out. 

I am using the Pico in a small camper. I'm trying to feed the data from the pico into the raspberry pi so I can push it out to an external server and monitor the system remotely. 

A bit overkill, but it looked like a fun project. 😀

**Comment by colonel-lp** [comment]
Hi nafkin2, 
Would you mind sharing your progress as this is exactly what I'm hoping to do too, I think there are quite a lot of other simarine users that would like to do this too. Quite happy to help test and contribute if I can, Pico and pi are installed and waiting to go.

**Comment by htool** [comment]
I also started with moving to Python3, but I notice the code chokes the Pico and requires reboots between tries. And since it's on the boat and I'm at home, progress isn't great. It would help me as well to see your Python3 progress.

**Comment by nafkin2** [comment]
Unfortunately I had to pause - the camper's transmission bit the dust on a trip so we had to leave it at a shop in another city. All of the project materials are on-board, including the computer with the code. 

When it is repaired and I can go pick it up, I will post the progress I've made so far.

**Comment by nafkin2** [comment]
I was able to retrieve the code, but I cannot continue testing until I can get the camper back in a few weeks. I've created a pull request to a WIP folder with what I have so far. The connection is working, and it is receiving data, but I don't have a method for associating the data with the correct sensors yet.

**Comment by htool** [comment]
> I was able to retrieve the code, but I cannot continue testing until I can get the camper back in a few weeks. I've created a pull request to a WIP folder with what I have so far. The connection is working, and it is receiving data, but I don't have a method for associating the data with the correct sensors yet.

Sorry to hear about the van. I hope the repairs will go well (and not too expensive). And thanks for sharing the code progress you've made so far!

**Comment by htool** [comment]
BTW, latest version has auto detection of config. If you go back a few version you can find it in python code (I moved to NodeJS due to SignalK compatibility)
